services:
  - type: web
    name: delhi-bhu-praman-portal
    env: python
    buildCommand: ""
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
